### PR TITLE
Fix PANTS_SHA install caching.

### LINKED ISSUE #173: Use of `PANTS_SHA` reexecutes some bootstrapping logic on each run
When `PANTS_SHA` is in use, a series of downloading lines flash by on every invoke.

### PR DESCRIPTION
**Pull request by jsirois**
Fixes #173

### CODE REVIEW

**Comment by jsirois** [comment]
I don't know of a good way to test this. Manually tested of course, but ensuring the result is cached requires poking at internals or turning off the network.

**Review by kaos — APPROVED** [review]
> I don't know of a good way to test this.

In what context is the `PANTS_VERSION_PROMPT_SALT` available?

Two subsequent runs should have the same salt when this works, right?

**Comment by jsirois** [comment]
> In what context is the PANTS_VERSION_PROMPT_SALT available?

Only when no Pants version is supplied (via pants.toml, PANTS_VERSION or PANTS_SHA)

> Two subsequent runs should have the same salt when this works, right?

They should have no PANTS_VERSION_PROMPT_SALT env var set at all, that was the bug. That's a very direct test of internals that doesn't do much though, I'm hoping for an IT, something that actually tests a back slide robust to details.

**Review by stuhood — APPROVED** [review]
Thanks!

----

Re: testing: yea, had the same realization for #172. I'm not sure what to do about that... maybe a Pants plugin which reports some details of the invoke? But it would be a big abstraction leak for any of that information to actually be exposed to plugins, so...

**Comment by kaos** [comment]
> > In what context is the PANTS_VERSION_PROMPT_SALT available?
> 
> Only when no Pants version is supplied (via pants.toml, PANTS_VERSION or PANTS_SHA)
> 
> > Two subsequent runs should have the same salt when this works, right?
> 
> They should have no PANTS_VERSION_PROMPT_SALT env var set at all, that was the bug. That's a very direct test of internals that doesn't do much though. I'm hoping for an IT, something that actually tests a back slide robust to details.

Oh right. Yea, in my mind it merely changed the value. 

Guess an IT would have to capture network traffic or something like that maybe in order to detect the side-effect of using PANTS_SHA or not. Feels like a lot of work for a relatively small feature.

**Pull request merged**
