### PR TITLE
Use Pants'-managed runs-on runners for Linux aarch64 CI

### LINKED ISSUE #422: Replace CircleCI ARM CI with Pantsbuild's runs-on runners
The main pants repo now uses "self-hosted" aarch64 linux runners, via runs-on and Pantsbuild's AWS account.

- https://github.com/pantsbuild/pants/pull/21325
- https://github.com/pantsbuild/pants/pull/21329
- https://github.com/pantsbuild/pants/pull/21330
- https://github.com/pantsbuild/pants/pull/21332

We can hopefully do the same here and simplify our configuration by only using Github Actions for CI instead of circle CI too.

We may want to move the pants repo config to be shared: https://runs-on.com/configuration/repo-config/#sharing-configuration-across-repositories

### LINKED ISSUE #430: Release CI fails to trigger CircleCI linux aarch64 build
The 0.12.1 build failed: https://github.com/pantsbuild/scie-pants/actions/runs/12041161791/job/33578047638

`Error: Error: Request failed with status code 403`

also related #422

### PR DESCRIPTION
**Pull request by huonw**
This replaces our use of Circle CI's arm64 Linux runners for both testing and releasing with the runs-on runners that Pantsbuild configures (and pays for) in AWS, via https://runs-on.com

This has a few benefits:

- single tool to learn for configuring CI
- single source of credentials (currently the release build is failing due to a token seemingly being invalid, but it's not obvious to me how to fix this)
- more atomicity, e.g. instead of the release needing to trigger a separate Circle CI build that runs in the background, we can just use the normal GitHub "wait for another job" rules

It also has downsides: we're going from free resources to paid. However, the incremental cost for the scie-pants repo should be quite small, compared to the main pants repo: 

- this repo is low volume (over the last 12 months we've done about 220 CI runs total)
- things run quickly (in this PR, ~7 minutes without a cache, ~4 minutes with)

I estimated cost based on US$0.1344/hour for a on-demand t4g.xlarge 4 core instance in us-east-1 (I'm not sure this is our exact configuration). Prices in practice may be cheaper, because Runs-On attempts to use [spot instances](https://runs-on.com/configuration/spot-instances/)).

- per build, we're looking at US$0.0090 (with cache) to US$0.016 (without cache)
- per month, we're looking at ~20 builds, so US$0.18 to US$0.32 (but likely cheaper given this is on-demand costs)

If this starts adding up a lot, we can likely optimise. For instance: optimise spot-instance selection for lowest cost not "PCO", and use more caching (whether that's coarse-grained `actions/cache` or fine-grained `sccache`).

Fixes #422, fixes #430

### CODE REVIEW

**Comment by huonw** [comment]
Where do I see that error? It's not in the GitHub UI that I can spot?

I'm imagining #428 (add the config to the `main` branch first) may help.

**Comment by benjyw** [comment]
> Where do I see that error? It's not in the GitHub UI that I can spot?
> 
> I'm imagining #428 (add the config to the `main` branch first) may help.

That error is in emails from RunsOn, but you can see CI stalling out on it here: https://github.com/pantsbuild/scie-pants/actions/runs/12019942836/job/33507556110?pr=427

**Comment by huonw** [comment]
To land this, someone with more repository admin powers than me will need to mark the circle CI jobs as not-required (and the linux-arm64 ones as required, while you're there).

Once this lands, I'll do a beta release to validate the release workflow changes.

**Comment by benjyw** [comment]
> To land this, someone with more repository admin powers than me will need to mark the circle CI jobs as not-required (and the linux-arm64 ones as required, while you're there).
> 
> Once this lands, I'll do a beta release to validate the release workflow changes.

The branch protection rules have been updated as requested.

**Review by benjyw — APPROVED** [review]

**Comment by benjyw** [comment]
BTW we still had a github webhook that triggered a no-op circleci build, which would display on the circleci side as an error due to lack of a circleci config file. This webhook has now been deleted.

**Pull request merged**
