### PR TITLE
Upgrade Pants's PEX to 2.1.137.

### PR DESCRIPTION
**Pull request by benjyw**
To match the one embedded in pbt.

### CODE REVIEW

**Comment by benjyw** [comment]
Before this change, `cargo run -p package -- test` failed with 

```
>> Verifying the tools.pex built by the package crate matches the tools.pex built by Pants
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"8ee6822086594dd83394f921c8bac0a25a8d70fa530522d59064062f3ba2b63f"`,
 right: `"e7bf24a357bd0d959614df1d2516d088e8e44497a354c615d415104d6f830d14"`', package/src/test.rs:288:9
```

With this change, `cargo run -p package -- test` passes.

**Review by huonw — APPROVED** [review]

**Comment by huonw** [comment]
Do you have ideas about why CI didn't catch this?

(I guess this may've been caused by https://github.com/pantsbuild/scie-pants/pull/259 ? although that was pinning PEX to 2.1.126, not .137 🤔 )

**Comment by benjyw** [comment]
I spoke too soon, https://github.com/pantsbuild/scie-pants/pull/274 is also required to get identical tools.pex.

**Comment by thejcannon** [comment]
If anything, I think we should have pbts version track the pants one... it'd be less to maintain

**Comment by thejcannon** [comment]
Also how does this relate to my original post in #development?
https://pantsbuild.slack.com/archives/C0D7TNJHL/p1694101689659639?thread_ts=1694101689.659639&cid=C0D7TNJHL


The metadata in pbt..toml doesn't use 137, it uses 134

**Pull request merged**
